# Rechte für `Alexa`@`localhost`

GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO 'Alexa'@'localhost' IDENTIFIED BY PASSWORD '*5118992DEC9E7D1902BE7A230BB827251E0FD90F' WITH MAX_USER_CONNECTIONS 1;

GRANT SELECT, INSERT, UPDATE, DELETE ON `alexasmalltalkemotion`.* TO 'Alexa'@'localhost';